#ifndef __SAMPLES_H__
#define __SAMPLES_H__

#define SAMPLE_BEEP 6
#define SAMPLE_BOOP 7
#define SAMPLE_CANCEL 8
#define SAMPLE_CRASH 9
#define SAMPLE_DOCK 10
#define SAMPLE_ECM 11
#define SAMPLE_EXPLODE 12
#define SAMPLE_GAMEOVER 13
#define SAMPLE_HITEM 14
#define SAMPLE_HYPER 15
#define SAMPLE_INCOM1 16
#define SAMPLE_INCOM2 17
#define SAMPLE_LAUNCH 18
#define SAMPLE_MISSILE 19
#define SAMPLE_PULSE 20
#define SAMPLE_SELECT 21

#endif
